services:
  - type: web
    name: tech-mobility-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        fromEnv: PORT
      - key: MONGO_USER
        fromEnv: MONGO_USER
      - key: MONGO_PASS
        fromEnv: MONGO_PASS
      - key: JWT_SECRET_WORD
        fromEnv: JWT_SECRET_WORD
      - key: ENCRYPTION_KEY
        fromEnv: ENCRYPTION_KEY
      - key: MONGODB_URI
        fromEnv: MONGODB_URI
